version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B clean package
      - run:
          name: Test and Generate Coverage Report
          command: mvn test jacoco:report
      - codecov/upload
      - persist_to_workspace:
          root: .
          paths:
            - target

  codecov-upload:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash) -f target/site/jacoco/jacoco.xml

workflows:
  version: 2
  build-and-test-and-upload:
    jobs:
      - build-and-test
      - codecov-upload:
          requires:
            - build-and-test

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}