version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:23.0
    steps:
      - checkout
      - run:
          name: Setup Maven
          command: mvn -version
      - run:
          name: Build With Maven
          command: mvn clean package -DskipTests

  test:
    docker:
      - image: cimg/openjdk:23.0
    steps:
      - checkout
      - run:
          name: Test With Maven
          command: mvn test jacoco:report
      - run:
          name: Generate JaCoCo Coverage Report
          command: mvn jacoco:report
      - codecov/upload

workflows:
  build_and_test_and_deploy:
    jobs:
      - build:
        filters:
          branches:
            only: master
      - test:
          requires:
            - build