version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B clean package
      - run:
          name: Test and Generate Coverage Report
          command: mvn test jacoco:report
      - run:
          name: List target directory
          command: ls -R target
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
          token: CODECOV_TOKEN
      - persist_to_workspace:
          root: .
          paths:
            - target

workflows:
  version: 2
  build-and-test-and-upload:
    jobs:
      - build-and-test
