version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:23.0
    steps:
      - checkout
      - run:
          name: Setup Maven
          command: mvn -version
      - run:
          name: Build With Maven
          command: mvn clean package -DskipTests

  test:
    docker:
      - image: cimg/openjdk:23.0
    steps:
      - checkout
      - run:
          name: Install xmllint
          command: sudo apt-get update && sudo apt-get install -y libxml2-utils
      - run:
          name: Test With Maven
          command: mvn test jacoco:report
      - run:
          name: Generate JaCoCo Coverage Report
          command: mvn jacoco:report
      - run:
          name: Run Checkstyle Analysis
          command: mvn checkstyle:checkstyle
      - run:
          name: Count Checkstyle Errors
          command: |
            errors=$(xmllint --xpath "count(//error)" target/checkstyle-result.xml)
            echo "export checkstyle_errors=$errors" >> $BASH_ENV
      - run:
          name: Update README.md with Badge
          command: |
            badge="![CheckStyle Badge](https://img.shields.io/badge/CheckStyle-${checkstyle_errors}-green)"
            
            if grep -q "CheckStyle Badge" README.md; then
              sed -i "s|!\[CheckStyle Badge\].*|$badge|" README.md
            else
              sed -i "/!\[CircleCI\]/a $badge" README.md
            fi
            
            if git diff --quiet; then
              echo "No changes to commit."
              exit 0
            else
              git config user.name "LucasLeiner"
              git config user.email "lucasleiner05@gmail.com"
              git add README.md
              git commit -m "Update Checkstyle Badge [ci skip]"
              git push https://LucasLeiner:${GH_TOKEN}@github.com/LucasLeiner/ceri-m1-techniques-de-test.git master
            fi

      - codecov/upload

workflows:
  build_and_test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
