version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:23.0
    steps:
      - checkout
      - run:
          name: Setup Maven
          command: mvn -version
      - run:
          name: Build With Maven
          command: mvn clean package -DskipTests

  test:
    docker:
      - image: cimg/openjdk:23.0
    steps:
      - checkout
      - run:
          name: Install xmllint
          command: sudo apt-get update && sudo apt-get install -y libxml2-utils
      - run:
          name: Test With Maven
          command: mvn test jacoco:report
      - run:
          name: Generate JaCoCo Coverage Report
          command: mvn jacoco:report
      - run:
          name: Run Checkstyle Analysis
          command: mvn checkstyle:checkstyle
      - run:
          name: Count Checkstyle Errors
          command: |
            errors=$(xmllint --xpath "count(//error)" target/checkstyle-result.xml)
            echo "checkstyle-errors=$errors" >> $BASH_ENV
      - run:
          name: Update README.md with Badge
          command: |
            echo "![CheckStyle Badge](https://img.shields.io/badge/CheckStyle-$checkstyle-errors-green)" > README.md
            git config user.name "LucasLeiner"
            git config user.email "lucasleiner05@gmail.com"
            git add README.md
            git commit -m "Update Checkstyle Badge"
            git push origin master
      - codecov/upload

workflows:
  build_and_test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
