version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - persist_to_workspace:
          root: .
          paths:
            - target

  codecov-upload:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash)

orbs:
  codecov: codecov/codecov@4.0.1

workflows:
  version: 2
  build-and-test-and-upload:
    jobs:
      - build-and-test
      - codecov-upload:
          requires:
            - build-and-test

  upload-to-codecov :
    jobs :
      - checkout
      - codecov/upload

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


  sample:
    jobs:
      - build-and-test