version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

# Define jobs
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      # Save the workspace (e.g., test results or reports) for the next job (like code coverage upload)
      - persist_to_workspace:
          root: .
          paths:
            - target

  codecov-upload:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      # Restore workspace data
      - attach_workspace:
          at: .
      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash)

# Define workflows
workflows:
  version: 2
  build-and-test-and-upload:
    jobs:
      - build-and-test
      - codecov-upload:
          requires:
            - build-and-test
