version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  # Below is the definition of your job to build and test your app.
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

  # Define a job to upload coverage data to Codecov
  codecov-upload:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash)

orbs:
  codecov: codecov/codecov@4.0.1

workflows:
  # Workflow for building and testing your app
  build-and-test-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master

  # Workflow for uploading coverage to Codecov
  upload-to-codecov:
    jobs:
      - codecov-upload:
          filters:
            branches:
              only:
                - master

env:
  CODECOV_TOKEN: d6203c06-61e3-492c-9b36-fab5437c3a01
