version: 2.1

# Define jobs
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      # Save the workspace (e.g., test results or reports) for the next job (like code coverage upload)
      - persist_to_workspace:
          root: .
          paths:
            - target

  codecov-upload:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      # Restore workspace data
      - attach_workspace:
          at: .
      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash)

orbs:
  codecov: codecov/codecov@4.0.1

workflows:
  version: 2
  build-and-test-and-upload:
    jobs:
      - build-and-test  # No additional configuration, just use the job name as a string
      - codecov-upload:  # Requires additional configuration, use it as a mapping
          requires:
            - build-and-test

  upload-to-codecov :
    jobs :
      - checkout
      - codecov/upload

env:
  CODECOV_TOKEN: d6203c06-61e3-492c-9b36-fab5437c3a01


  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test
